# Generated by Django 5.2.12 on 2026-06-13 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_interviewquestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewquestion',
            name='category',
            field=models.CharField(choices=[('Java', 'Java'), ('Python', 'Python'), ('JS', 'JS'), ('CSS', 'CSS')], max_length=100),
        ),
    ]
