# Generated by Django 5.2.12 on 2026-06-14 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_interviewquestion_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApptitudeQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Java', 'Java'), ('Python', 'Python'), ('JS', 'JS'), ('CSS', 'CSS')], max_length=100)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
            ],
        ),
    ]
