# Generated by Django 5.2.12 on 2026-06-19 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_apptitudequestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('Java', 'Java'), ('Python', 'Python'), ('JS', 'JS'), ('c++', 'c++'), ('html', 'html'), ('css', 'css'), ('sql', 'sql')], max_length=10),
        ),
    ]
